Us/nav bar - Navbar added to project file on more appropriately named branch
WildCodeSchool/noname pull request #10
Opened 2022-10-27 12:04 UTC by td6904

2022-10-27 12:31 UTC, ikolan approved these changes

2022-10-27 13:20 UTC, Benja-san requested changes

2022-10-27 13:20 UTC, Benja-san commented on public/assets/css/nav.css
> +    background-color: #4981A6;
use global variables for colors supposed to be injected in multiples items

2022-10-27 13:20 UTC, Benja-san commented on src/View/nav.html.twig
> +	<div class="main">
Could you transform this div tag into an Ul since it will be a list of links, and define each child element as a li

2022-10-27 13:20 UTC, Benja-san commented on src/View/nav.html.twig
> +		<a href="" {# Enter link here #}>
wrap it into a li, could you properly indent your tag

2022-10-27 13:20 UTC, Benja-san commented on src/View/nav.html.twig
> +			<a href="" {# Enter link here #}><img src="../assets/images/Vector.png"></a>
Could your wrap all thos A into a ul (descendant of an Li) and then wrap all a into li tags ?

2022-10-27 13:20 UTC, Benja-san commented on src/View/nav.html.twig
> +<nav class="mobile-nav">
Could you wrapp your a tags into a UL tag and wrap all A into li tags

2022-11-02 13:23 UTC, Benja-san requested changes

2022-11-02 13:23 UTC, Benja-san commented on public/assets/css/nav.css
> +
this global behavio should be in global css file

2022-11-02 13:23 UTC, Benja-san commented on src/View/nav.html.twig
> +	<ul class="menu" id="icons" onclick="searchHide();"></li>
end of li tag should not be here, related to nothing

2022-11-02 13:23 UTC, Benja-san commented on src/View/nav.html.twig
> +</ul></header><nav><!-- Quick access categories --><ul class="quick-access">
please indent properly

2022-11-02 13:23 UTC, Benja-san commented on src/View/nav.html.twig
> +	<div class="line"></div>
should be a li tag or if it is just for "display" behavior, it should not be present here but inside the li targeted

2022-11-02 16:30 UTC, Benja-san approved these changes

2022-11-02 16:30 UTC, Benja-san commented on .gitignore
> +footer.html.twig
why ?

2022-11-03 08:02 UTC, merged