Us/homepage
WildCodeSchool/noname pull request #12
Opened 2022-11-02 16:09 UTC by Markus0059

2022-11-03 08:25 UTC, td6904 approved these changes

2022-11-03 08:37 UTC, td6904 approved these changes

2022-11-03 13:54 UTC, Benja-san requested changes

2022-11-03 13:54 UTC, Benja-san commented on src/View/CategoryItem/index.html.twig
> +                <img src="{{categoryItem.logo}}" alt="" class="logo-card-category" style="background-color: white">
Please put an alt content "mandatory for disabled users"

2022-11-04 08:48 UTC, Markus0059 commented on src/View/CategoryItem/index.html.twig
> +                <img src="{{categoryItem.logo}}" alt="" class="logo-card-category" style="background-color: white">
it's ok

2022-11-04 09:10 UTC, td6904 approved these changes

2022-11-04 09:46 UTC, Benja-san approved these changes

2022-11-04 11:19 UTC, merged