Search products by word and/or category
WildCodeSchool/noname pull request #14
Opened 2022-11-03 13:16 UTC by ikolan

2022-11-04 09:09 UTC, td6904 approved these changes

2022-11-04 09:56 UTC, Benja-san requested changes

2022-11-04 09:56 UTC, Benja-san commented on src/View/Product/index.html.twig
> +	<div class="productListButtons">
please wrap html content inside a main tag

2022-11-04 09:56 UTC, Benja-san commented on src/View/_macros/productCard.html.twig
>  	<div class="productCardContainer">
replace div tag by ul tag since it will be a list of cards

2022-11-04 09:56 UTC, Benja-san commented on src/View/_macros/productCard.html.twig
> +			<div class="products">
replace div tag by li tag

2022-11-04 11:36 UTC, td6904 approved these changes

2022-11-04 11:40 UTC, Benja-san approved these changes

2022-11-07 14:17 UTC, Markus0059 approved these changes

2022-11-07 14:17 UTC, merged