Us/homepage
WildCodeSchool/noname pull request #6
Opened 2022-10-25 15:15 UTC by Markus0059

The Homepage is finished with the display of the latest products.
Adding the CategoryItem Index page with the Add form in it.

2022-10-26 09:10 UTC, ikolan requested changes

2022-10-26 09:10 UTC, n3en commented on public/assets/css/formCategoryItem.css
> +  border: solid 0.5px var(--lessblueColor)!important;
`!important` is considered as a bad practice.

2022-10-26 09:10 UTC, ikolan commented on src/Model/AbstractManager.php
> +    // public function selectlast(int $limit = 1): array
Avoid commented code

2022-10-26 09:10 UTC, ikolan commented on src/View/Home/index.html.twig
> -				{# {% for item in items| %}
Commented code

2022-10-26 19:02 UTC, Markus0059 commented on public/assets/css/formCategoryItem.css
> +  border: solid 0.5px var(--lessblueColor)!important;
I changed the class border in my HTML because there was opposition with bootstrap

2022-10-26 19:02 UTC, Markus0059 commented on src/Model/AbstractManager.php
> +    // public function selectlast(int $limit = 1): array
ok i deleted it

2022-10-26 19:03 UTC, Markus0059 commented on src/View/Home/index.html.twig
> -				{# {% for item in items| %}
ok i deleted it

2022-10-26 22:12 UTC, Markus0059 commented
it ok for a new review

2022-10-26 22:17 UTC, Markus0059 commented on src/View/_macros/pageSwitcher.html.twig
> +			class="pageSwitcher">
je fais la correction

2022-10-26 22:18 UTC, Markus0059 commented on src/View/_macros/pageSwitcher.html.twig
> +			class="pageSwitcher">
it 's ok after review

2022-10-27 08:15 UTC, ikolan approved these changes

2022-10-27 08:58 UTC, Benja-san requested changes

2022-10-27 08:58 UTC, Benja-san commented on src/Controller/CategoryItemController.php
> +    public function checkdata($data): array
if this function does not need to be used outside the class, change it as a private method

2022-10-27 08:58 UTC, Benja-san commented on src/Model/CategoryItemManager.php
> +            $query = "UPDATE " . self::TABLE . " SET in_carousel = TRUE where id= " . $item['id'];
Works for now but can be optimized (optional)
You can loop only on the query rather than execute a db request on each update

2022-10-27 08:58 UTC, Benja-san commented on src/View/CategoryItem/add.html.twig
> +		<h1 class="text-center">Ajoutes une nouvelle catégorie</h1>
increment h tags + 1 since you can ony have one h1 by page (the one in categoryItems index)

2022-10-27 08:58 UTC, Benja-san commented on src/View/CategoryItem/index.html.twig
> +	<div class="container">
main tag would be better

2022-10-27 14:08 UTC, ikolan approved these changes

2022-10-27 14:22 UTC, Benja-san approved these changes

2022-10-27 14:23 UTC, merged