Show product
WildCodeSchool/noname pull request #7
Opened 2022-10-26 13:17 UTC by Guillaum6e

1er aperçu de la page showProduct

2022-10-26 13:33 UTC, ikolan approved these changes
More comments would be helpful.

2022-10-27 08:43 UTC, Benja-san requested changes

2022-10-27 08:43 UTC, Benja-san commented on public/assets/css/show.css
> +* {
Since this is a global behavior, please put this code inside the global css file

2022-10-27 08:43 UTC, Benja-san commented on public/assets/css/show.css
> +body {
this as well

2022-10-27 08:43 UTC, Benja-san commented on public/assets/css/show.css
> +span {
please put a class name or put this span in a BEM otherwise all the span of the show page will take this behavior

2022-10-27 08:43 UTC, Benja-san commented on src/View/Product/show.html.twig
> +            <div>
does this div as a meaning? if not suppress it

2022-10-27 08:43 UTC, Benja-san commented on src/View/Product/show.html.twig
> +        <article class="product_description2">
I think a ul li display would have more sense, since it will be a list of product description

2022-10-27 08:43 UTC, Benja-san commented on src/View/Product/show.html.twig
> +            <div class="product_image" id="product_imgs">
ul and li tags would be better since it is a list of images, please change the classname "product_image as "product_images" for better understanding. Also I am not against the snake case, but please see with the group to get a unique global naming style (to avoid camel case and snake case mix)

2022-10-27 08:43 UTC, Benja-san commented on src/View/Product/show.html.twig
> +            <div class="product_seller_location"><span>Habite:</span> FortFortLointain</div>
optional, you can add an address tag for location

2022-10-27 11:49 UTC, Benja-san approved these changes
All Good !

2022-10-27 11:50 UTC, merged