Us/form add product
WildCodeSchool/noname pull request #9
Opened 2022-10-27 09:59 UTC by moioms

2022-11-03 13:11 UTC, td6904 approved these changes

2022-11-03 14:15 UTC, Benja-san requested changes
Requested changes on Omar's code, global team review required for lib and architectural code updated inside the PR

2022-11-03 14:15 UTC, Benja-san commented on public/assets/css/form_products.css
> +form {
please use classname instead of tags, otherwise all form tags will take this behavior

2022-11-03 14:15 UTC, Benja-san commented on public/assets/css/form_products.css
> +    background-color: #4981A6;
if it is a global color, please use a variable set in global css file

2022-11-03 14:15 UTC, Benja-san commented on public/assets/css/form_products.css
> +textarea {
also use class name

2022-11-03 14:15 UTC, Benja-san commented on public/assets/css/form_products.css
> +    border-bottom: 2px solid #4981A6;
variable name for color

2022-11-03 14:15 UTC, Benja-san commented on public/assets/css/form_products.css
> +    background-color: #4981a6;
variable name for color

2022-11-03 14:15 UTC, Benja-san commented on public/assets/css/form_products.css
> +    background-color: #4981a68e;
variable name for color ?

2022-11-03 14:15 UTC, Benja-san commented on public/assets/js/form_products.js
> +function remplace_click(event) {
"replace" instead of "remplace"

2022-11-03 14:15 UTC, Benja-san commented on src/Controller/ProductController.php
> +            var_dump($_FILES['file']['name'][0]);
remove useless var dumps

2022-11-03 14:15 UTC, Benja-san commented on src/Model/ProductManager.php
> +        $statement->bindValue(`category_item_id`, $product['category'], PDO::PARAM_STR);
this entry should be an integer

2022-11-03 14:15 UTC, Benja-san commented on src/View/Product/form.html.twig
> +    <h3 class="h3">Titre</h3>
where is the h2?

2022-11-03 14:15 UTC, Benja-san commented on src/Controller/ProductController.php
> +            "post" => $_POST
I'm quite sure you don't need this post entry

2022-11-04 09:12 UTC, td6904 approved these changes

2022-11-04 09:45 UTC, Benja-san approved these changes
Read and confirm the comment I left, if no changes necessaries you can merge on dev

2022-11-04 09:45 UTC, Benja-san commented on src/Model/ProductManager.php
> +        $statement->bindValue(`category_item_id`, $product['category'], PDO::PARAM_INT);
Can you cnfirm the category key retrieved will be equal to the category_id and not the category name ?

2022-11-04 13:03 UTC, merged